In [1]:
import fastf1

In [2]:
import pandas as pd

In [3]:
import sys
sys.path.append('../src')

from data_loader import processar_quali

In [4]:
processar_quali(2025, 'Bahrain')

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '16', '12', '10', '4', '1', '55', '44', '22', '7', '6', '14', '31', '23', '27', '30', '5', '18', '87']

,Piloto,Equipe,S1,S2,S3,Tempo de Volta,Position,Ano,GP
0,PIA,McLaren,28.784,38.574,22.483,89.841,1,2025,Bahrain Grand Prix
1,RUS,Mercedes,28.771,38.710,22.528,90.009,2,2025,Bahrain Grand Prix
2,LEC,Ferrari,28.926,38.714,22.535,90.175,3,2025,Bahrain Grand Prix
3,ANT,Mercedes,28.836,38.786,22.591,90.213,4,2025,Bahrain Grand Prix
4,GAS,Alpine,28.883,38.694,22.639,90.216,5,2025,Bahrain Grand Prix
5,NOR,McLaren,29.007,38.678,22.582,90.267,6,2025,Bahrain Grand Prix
6,VER,Red Bull Racing,28.880,38.855,22.688,90.423,7,2025,Bahrain Grand Prix
7,SAI,Williams,28.894,39.063,22.723,90.680,8,2025,Bahrain Grand Prix
8,HAM,Ferrari,28.955,39.058,22.759,90.772,9,2025,Bahrain Grand Prix
9,TSU,Red Bull Racing,29.067,39.177,22.984,91.228,10,2025,Bahrain Grand Prix
10,DOO,Alpine,29.094,39.215,22.936,91.245,11,2025,Bahrain Grand Prix
11,HAD,Racing Bulls,29.081,39.267,22.923,91.271,12,2025,Bahrain Grand Prix
12,ALO,Aston Martin,29.231,39.502,22.901,91.634,13,2025,Bahrain Grand Prix
13,OCO,Haas F1 Team,29.154,39.527,22.913,91.594,14,2025,Bahrain Grand Prix
14,ALB,Williams,29.227,39.776,23.037,92.040,15,2025,Bahrain Grand Prix
15,HUL,Kick Sauber,29.400,39.490,23.177,92.067,16,2025,Bahrain Grand Prix
16,LAW,Racing Bulls,29.327,39.880,22.958,92.165,17,2025,Bahrain Grand Prix
17,BOR,Kick Sauber,29.577,39.608,23.001,92.186,18,2025,Bahrain Grand Prix
18,STR,Aston Martin,29.282,39.858,23.143,92.283,19,2025,Bahrain Grand Prix
19,BEA,Haas F1 Team,29.319,40.089,22.965,92.373,20,2025,Bahrain Grand Prix

## --------------------------------------------------------------------------------------- ##

In [5]:
calendario = fastf1.get_event_schedule(2025)
calendario[['RoundNumber', 'EventName', 'Country', 'EventDate']]

    RoundNumber                  EventName               Country  EventDate
0             0         Pre-Season Testing               Bahrain 2025-02-28
1             1      Australian Grand Prix             Australia 2025-03-16
2             2         Chinese Grand Prix                 China 2025-03-23
3             3        Japanese Grand Prix                 Japan 2025-04-06
4             4         Bahrain Grand Prix               Bahrain 2025-04-13
5             5   Saudi Arabian Grand Prix          Saudi Arabia 2025-04-20
6             6           Miami Grand Prix         United States 2025-05-04
7             7  Emilia Romagna Grand Prix                 Italy 2025-05-18
8             8          Monaco Grand Prix                Monaco 2025-05-25
9             9         Spanish Grand Prix                 Spain 2025-06-01
10           10        Canadian Grand Prix                Canada 2025-06-15
11           11        Austrian Grand Prix               Austria 2025-06-29
12           12         British Grand Prix        United Kingdom 2025-07-06
13           13         Belgian Grand Prix               Belgium 2025-07-27
14           14       Hungarian Grand Prix               Hungary 2025-08-03
15           15           Dutch Grand Prix           Netherlands 2025-08-31
16           16         Italian Grand Prix                 Italy 2025-09-07
17           17      Azerbaijan Grand Prix            Azerbaijan 2025-09-21
18           18       Singapore Grand Prix             Singapore 2025-10-05
19           19   United States Grand Prix         United States 2025-10-19
20           20     Mexico City Grand Prix                Mexico 2025-10-26
21           21       São Paulo Grand Prix                Brazil 2025-11-09
22           22       Las Vegas Grand Prix         United States 2025-11-22
23           23           Qatar Grand Prix                 Qatar 2025-11-30
24           24       Abu Dhabi Grand Prix  United Arab Emirates 2025-12-07

In [6]:
corridas = calendario[calendario['RoundNumber'] > 0]
corridas[['RoundNumber', 'EventName']]

    RoundNumber                  EventName
1             1      Australian Grand Prix
2             2         Chinese Grand Prix
3             3        Japanese Grand Prix
4             4         Bahrain Grand Prix
5             5   Saudi Arabian Grand Prix
6             6           Miami Grand Prix
7             7  Emilia Romagna Grand Prix
8             8          Monaco Grand Prix
9             9         Spanish Grand Prix
10           10        Canadian Grand Prix
11           11        Austrian Grand Prix
12           12         British Grand Prix
13           13         Belgian Grand Prix
14           14       Hungarian Grand Prix
15           15           Dutch Grand Prix
16           16         Italian Grand Prix
17           17      Azerbaijan Grand Prix
18           18       Singapore Grand Prix
19           19   United States Grand Prix
20           20     Mexico City Grand Prix
21           21       São Paulo Grand Prix
22           22       Las Vegas Grand Prix
23           23           Qatar Grand Prix
24           24       Abu Dhabi Grand Prix

In [7]:
tabelas = []
falhas = []

for rodada in corridas['RoundNumber']:
    try:
         tabela = processar_quali(2025, rodada)
         tabelas.append(tabela)
    except Exception as e:
        print(f"Falha na rodada {rodada}: {e}")
        falhas.append(rodada)

len(tabelas), falhas

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '16', '12', '10', '4', '1', '55', '44', '22', '7', '6', '14', '31', '23', '27', '30', '5', '18', '87']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '63', '16', '12', '55', '44', '22', '10', '4', '23', '30', '14', '6', '87', '18', '7', '27', '31', '5']
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '12', '81', '63', '55', '23', '16', '31', '22', '6', '44', '5', '7', '30', '27', '14', '10', '18', '87']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '63', '4', '14', '55', '23', '18', '6', '10', '16', '44', '12', '5', '43', '30', '87', '27', '31', '22']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '44', '1', '6', '14', '31', '30', '23', '55', '22', '27', '63', '12', '5', '87', '10', '18', '43']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '63', '44', '12', '16', '10', '6', '14', '23', '5', '30', '18', '87', '27', '31', '55', '43', '22']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '44', '14', '4', '16', '6', '23', '22', '43', '27', '87', '31', '5', '55', '18', '30', '10']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '44', '63', '30', '1', '5', '12', '10', '14', '23', '6', '43', '87', '18', '31', '22', '55', '27']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '44', '16', '12', '87', '14', '10', '55', '22', '6', '23', '31', '30', '5', '18', '27', '43']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '1', '23', '63', '22', '6', '30', '5', '31', '87', '10', '27', '55', '44', '43', '12', '14', '18']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '63', '14', '18', '5', '1', '30', '6', '87', '44', '55', '43', '12', '22', '10', '31', '27', '23']
core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '6', '63', '16', '44', '30', '55', '14', '12', '22', '5', '10', '23', '43', '27', '31', '87', '18']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '63', '12', '5', '14', '22', '87', '27', '55', '23', '31', '6', '18', '43', '10', '30']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '55', '30', '12', '63', '22', '4', '6', '81', '16', '14', '44', '5', '18', '87', '43', '27', '10', '23', '31']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '4', '44', '16', '6', '87', '14', '27', '30', '22', '5', '18', '43', '31', '10', '23', '55']
core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '63', '44', '81', '12', '87', '55', '14', '27', '30', '22', '10', '43', '5', '31', '18', '23', '6']
core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '44', '63', '1', '12', '55', '81', '6', '87', '22', '31', '27', '14', '30', '5', '23', '10', '18', '43']
core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 5
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '12', '16', '81', '6', '63', '30', '87', '10', '27', '14', '23', '44', '18', '55', '1', '31', '43', '22', '5']
core           INFO 	Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data

(24, [])

In [8]:
processar_quali(2025, 1)

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

,Piloto,Equipe,S1,S2,S3,Tempo de Volta,Position,Ano,GP
0,NOR,McLaren,25.961,16.997,32.138,75.096,1,2025,Australian Grand Prix
1,PIA,McLaren,26.082,16.952,32.146,75.180,2,2025,Australian Grand Prix
2,VER,Red Bull Racing,26.066,16.915,32.500,75.481,3,2025,Australian Grand Prix
3,RUS,Mercedes,26.163,16.951,32.432,75.546,4,2025,Australian Grand Prix
4,TSU,Racing Bulls,26.190,17.005,32.475,75.670,5,2025,Australian Grand Prix
5,ALB,Williams,26.215,16.978,32.544,75.737,6,2025,Australian Grand Prix
6,LEC,Ferrari,26.194,17.025,32.536,75.755,7,2025,Australian Grand Prix
7,HAM,Ferrari,26.150,17.223,32.546,75.919,8,2025,Australian Grand Prix
8,GAS,Alpine,26.293,17.087,32.600,75.980,9,2025,Australian Grand Prix
9,SAI,Williams,26.269,17.078,32.584,75.931,10,2025,Australian Grand Prix
10,HAD,Racing Bulls,26.345,17.148,32.682,76.175,11,2025,Australian Grand Prix
11,ALO,Aston Martin,26.300,17.107,32.881,76.288,12,2025,Australian Grand Prix
12,STR,Aston Martin,26.474,17.151,32.744,76.369,13,2025,Australian Grand Prix
13,DOO,Alpine,26.381,17.150,32.784,76.315,14,2025,Australian Grand Prix
14,BOR,Kick Sauber,26.495,17.220,32.801,76.516,15,2025,Australian Grand Prix
15,ANT,Mercedes,26.443,17.166,32.916,76.525,16,2025,Australian Grand Prix
16,HUL,Kick Sauber,26.656,17.201,32.722,76.579,17,2025,Australian Grand Prix
17,LAW,Red Bull Racing,26.819,17.362,32.913,77.094,18,2025,Australian Grand Prix
18,OCO,Haas F1 Team,26.686,17.206,33.255,77.147,19,2025,Australian Grand Prix

In [9]:
df_temporada = pd.concat(tabelas, ignore_index=True)
df_temporada.shape

(475, 9)

In [10]:
df_temporada['GP'].nunique()

24

In [11]:
df_temporada.to_csv('../data/processed/quali_2025.csv', index=False)

## Coleta de dados — temporada 2025

**Objetivo:** a função `processar_quali(ano, gp)` recebe o ano e o GP (nome ou número da rodada) e devolve uma tabela com uma linha por piloto, contendo equipe, tempos de setor (S1, S2, S3), tempo de volta e posição de grid.

**Como funciona:**
- Carrega a sessão de quali daquele GP e pega a melhor volta cronometrada de cada piloto
- Junta essa tabela com `session.results` pela abreviação do piloto (nunca pela ordem das linhas — a ordem pode não significar nada)
- Converte os tempos, que vêm como `Timedelta`, para segundos com `.total_seconds()`

**Bugs encontrados e corrigidos:**
1. **Piloto sem volta rápida:** `pick_fastest()` devolve `None` quando o piloto não tem nenhuma volta cronometrada válida na sessão (ex: Bearman bateu no treino livre da Austrália 2025 e não rodou no quali). Sem checar isso, a linha seguinte (`volta['Driver']`) quebra com `'NoneType' object is not subscriptable`. A correção pula esse piloto com `if volta is None: continue`.

**Loop pela temporada:** percorri as 24 corridas de 2025 (filtrando a Rodada 0, que é a pré-temporada e não tem quali) com `try/except`, pra garantir que uma falha numa corrida não derrubasse o processamento das outras.

**Resultado:** 475 linhas de um teórico máximo de 480 (24 corridas × 20 pilotos) — a diferença de 5 vem de pilotos sem volta cronometrada em alguma sessão ao longo do ano.

**Onde ficou salvo:** `data/processed/quali_2025.csv`